---
name: Approve Release

on:
  pull_request:
    types:
      - opened
concurrency:
  group: approve-release
  cancel-in-progress: false
jobs:
  draft:
    name: Convert to draft
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.pull_request.draft == false && ! contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - name: Checkout hoprnet repository
        uses: actions/checkout@v3

      - name: Approve
        run: |
          gh pr review --approve
          gh pr merge --auto --delete-branch --squash 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
