---
name: Close Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        required: true
        description: 'Type of Release to create'
        options:
          - ReleaseCandidate
          - Patch
          - Minor
          - Major
      release_name:
        type: choice
        required: true
        description: 'Name of the release'
        options:
          - providence

concurrency:
  group: close-release
  cancel-in-progress: true

jobs:
  close-release:
    name: Close Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hoprnet repository
        uses: actions/checkout@v3

      - name: Choose template
        id: template
        run: |
          current_version=$(jq -r '.version' packages/hoprd/package.json)
          if [[ "${{ github.ref_name }}" = "master" ]] && [[ ${current_version} == *"-rc."* ]]
          then 
            echo "pr_template=pr-close-release.md" >> $GITHUB_OUTPUT
          else
            echo "pr_template=pr-close-patch.md" >> $GITHUB_OUTPUT
          fi
          echo "current_version=${current_version}" >> $GITHUB_OUTPUT

          milestone_number=$(gh api repos/${{ github.repository.name }}/milestones | jq -r --argjson version ${current_version}  ' to_entries[] | select(.value.title | test("$version")).value.number')
          ./scripts/generate-changelog.sh ${milestone_number} > changelog-${current_version}.md

        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
            commit-message: "Close release ${{ steps.template.outputs.current_version }}"
            title: "Close release ${{ steps.template.outputs.current_version }}"
            body-path: .github/files/${{ steps.template.outputs.pr_template }}
            branch: feature/close-${{ steps.template.outputs.current_version }}
            delete-branch: true
            labels: release
            assignees: ${{ github.actor }}
            reviewers: ausias-armesto
            #reviewers: hopr-version-bot
            #team-reviewers: hoprnet/hopr-development

      - name: Enable Auto Merge
        run: |
            git fetch
            git checkout feature/close-${{ steps.template.outputs.current_version }}
            gh pr merge --auto --delete-branch --squash
        env:
          GH_TOKEN: ${{ secrets.COMMIT_BOT_ACCESS_TOKEN }}
